from .settings import (
    GROQ_API_KEY,
    SERPER_API_KEY,
    SUPABASE_URL,
    SUPABASE_KEY,
    DEFAULT_MODEL,
    SEARCH_RESULTS_COUNT,
    FREE_MONTHLY_LIMIT,
    PRO_MONTHLY_LIMIT,
    OUTPUT_DIR,
    DEFAULT_LANGUAGE,
)
